---
title: 'PDX: Mice influence'
author: "Alistair Martin"
date: '`r format(Sys.time(), "Last modified: %d %b %Y")`'
output:
  html_document:
    toc: yes
    toc_float: yes
  html_notebook:
    toc: yes
    toc_float: yes
subtitle: Model AB861
layout: page
---

#Load libraries and data
```{r, message=FALSE, warning=FALSE}
library(dendextend)

root.dir <- "~/OneDrive/projects/"
source(paste0(root.dir,"R.utils/RNASEQ.utils.R"))

project.dir <- paste0(root.dir,"PDX/")
source(paste0(project.dir,"src/load.PDX.R"))
rnaseq <- get.PDX()
meta <- load.meta()

meta <- subset.meta(meta,meta[,project=="metastasis" & patient=="AB861"])
rnaseq <- subset.PDX(rnaseq, rnaseq$meta[,Sample.name] %in% meta[,Sample.name])
```

```{r}
read.depth.plots(rnaseq$meta)
```

```{r}
rnaseq <- merge.PDX(rnaseq)
rnaseq$meta <- merge(rnaseq$meta,meta,sort=F)
rnaseq$meta[,merged.lanes:=abbreviate(merged.lanes)]
```

# PCAs

```{r}
rnaseq <- subset.PDX(rnaseq,rnaseq$meta[,xenograft==TRUE])
```

```{r}
pca <- pca.run(rnaseq$human,rename = TRUE)
pca <- cbind(pca,rnaseq$meta)
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=merged.lanes))
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=tissue.grafted))
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=exp.protocol))
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=Batch))
```

Clear batch effect from sequencing and the experimental technique.

```{r}
pca <- pca.prep(rnaseq$human)
pca <- removeBatchEffect(pca, batch=rnaseq$meta[,merged.lanes], batch2 = rnaseq$meta[,exp.protocol], design=rnaseq$meta[,model.matrix(~tissue.sampled * tissue.grafted)])
pca <- pca.run.sub(pca,rename = T)
pca <- cbind(pca,rnaseq$meta)
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=merged.lanes))
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=tissue.grafted))
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=tissue.sampled))
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=exp.protocol))
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=Batch))
```


```{r}
pca <- pca.prep(rnaseq$mouse)
pca <- removeBatchEffect(pca, batch=rnaseq$meta[,merged.lanes], batch2 = rnaseq$meta[,exp.protocol], design=rnaseq$meta[,model.matrix(~tissue.sampled * tissue.grafted)])
pca <- pca.run.sub(pca,rename = T)
pca <- cbind(pca,rnaseq$meta)
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=merged.lanes))
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=tissue.grafted))
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=tissue.sampled))
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=exp.protocol))
ggpairs(pca,columns = 1:3,mapping = aes(shape=tissue.sampled,colour=Batch))
```

# Dendos

```{r}
x <- list(
  human=pca.prep(rnaseq$human),
  mouse=pca.prep(rnaseq$mouse),
  combined=rbind(pca.prep(rnaseq$human),pca.prep(rnaseq$mouse))
)
  
dendos <- lapply(x, function(y){
  y <- removeBatchEffect(y, batch=rnaseq$meta[,merged.lanes], batch2 = rnaseq$meta[,exp.protocol], design=rnaseq$meta[,model.matrix(~tissue.sampled * tissue.grafted)])
  y <- t(scale(t(y)))
  colnames(y) <- as.character(1:nrow(rnaseq$meta))
  dendo <- as.dendrogram(hclust(dist(t(y),method = "euclidean")))
  i <- as.numeric(labels(dendo))
  dendo <- set(dendo,"labels_col",value=rnaseq$meta[i,as.numeric(factor(tissue.grafted,levels = c("AB861M","AB861M-XT1","AB861M-XT1-XM1","AB861M-XT1-XM1-XM1","AB861M-XT1-XM1-XT1")))])
  dendo <- set(dendo,"leaves_pch",value=19)
  dendo <- set(dendo,"leaves_cex",value=2)
  dendo <- set(dendo,"leaves_col",value=rnaseq$meta[i,as.numeric(factor(tissue.sampled,levels = c("T","LN")))])
  dendo
})
```

```{r}
dl1 <- dendlist(dendos$human,dendos$combined)
dl1 <- untangle(dl1,method="step2side")

dl2 <- dendlist(dendos$mouse,dl1[[2]])
dl2 <- untangle(dl2,method="step1side")
dl2 <- rev(dl2)

layout(matrix(1:6, nrow=1, byrow=TRUE), widths=rep(c(5, 3, 5), 2))
tanglegram(dl1[[1]],dl1[[2]],sort=F,highlight_branches_lwd = F, highlight_distinct_edges=F,common_subtrees_color_lines = F,just_one = F,main_left = "Human",main_right = "Combined")
tanglegram(dl2[[1]],dl2[[2]],sort=F,highlight_branches_lwd = F, highlight_distinct_edges=F,common_subtrees_color_lines = F,just_one = F,main_right = "Mouse")
```



```{r}
corrplot(cor.dendlist(dendlist(human=dendos$human,combined=dendos$combined,mouse=dendos$mouse)), "pie", "lower")
```

#IGP

https://academic.oup.com/biostatistics/article/8/1/9/251048#2979265

```{r}
x <- list(
  human=pca.prep(rnaseq$human),
  mouse=pca.prep(rnaseq$mouse),
  combined=rbind(pca.prep(rnaseq$human),pca.prep(rnaseq$mouse))
)

nns <- lapply(x, function(y){
  y <- removeBatchEffect(y, batch=rnaseq$meta[,merged.lanes], batch2 = rnaseq$meta[,exp.protocol], design=rnaseq$meta[,model.matrix(~tissue.sampled * tissue.grafted)])
  y <- t(scale(t(y)))
  #colnames(y) <- as.character(1:nrow(rnaseq$meta))
  d <- as.matrix(dist(t(y),method = "euclidean"))
  diag(d) <- NA
  apply(d,1,which.min)
})

assigned.groups <- rnaseq$meta[,interaction(tissue.grafted,tissue.sampled,drop = T)]
x <- lapply(nns,function(nn){
  x <- lapply(levels(assigned.groups),function(group){
    i <- which(assigned.groups==group)
    sum(nn[i] %in% i) / length(i)
  })
  names(x) <- levels(assigned.groups)
  as.data.table(x)
})
x$N <- as.data.table(t(as.matrix.Vector(table(assigned.groups))))
x <- rbindlist(x,idcol = "data")
```

```{r}
y <- melt(x,id.vars = "data")
ggplot(y[data!="N"]) + aes(x=variable,y=value,fill=data) + geom_col(position="dodge") + 
  geom_text(aes(label=value,y=-.05),data=y[data=="N"]) + 
  theme_tufte(20) + theme(axis.text.x = element_text(angle = 90,hjust=1))
```


```{r}